# Generated by Django 3.2.4 on 2021-07-30 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospede', '0004_alter_hospede_email'),
        ('quarto_cama', '0001_initial'),
        ('funcionario', '0003_alter_funcionario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospede.hospede')),
            ],
        ),
        migrations.CreateModel(
            name='status_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reserva_cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarto_cama.cama')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
                ('status_reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.status_reserva')),
            ],
        ),
    ]
