# Generated by Django 3.2.4 on 2021-08-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_reserva',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
