# Generated by Django 3.2.4 on 2021-08-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0002_alter_status_reserva_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('valor_total', models.FloatField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
            ],
        ),
    ]
